# Generated by Django 4.2.5 on 2023-09-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='default_profile_image.png', upload_to='profile_images'),
        ),
    ]
